FROM --platform=linux/arm64 ubuntu:22.04

# Install system dependencies
RUN apt-get update && apt-get install -y \
    curl build-essential libgmp-dev libffi-dev libncurses-dev libtinfo-dev \
    libsqlite3-dev libsystemd-dev libsodium-dev libblas-dev liblapack-dev \
    autoconf libtool jq vim liblzma-dev libleveldb-dev libpq-dev pkg-config git xz-utils \
    libnuma-dev

# Install GHC for ARM64
RUN curl -L https://downloads.haskell.org/~ghc/9.6.3/ghc-9.6.3-aarch64-deb10-linux.tar.xz | tar -xJ && \
    cd ghc-9.6.3-aarch64-unknown-linux && ./configure --prefix=/usr/local && make install && cd .. && rm -rf ghc-9.6.3-aarch64-unknown-linux

# Install Stack for ARM64
RUN curl -sSL https://get.haskellstack.org/ | sh

# Build and install secp256k1
RUN git clone https://github.com/blockapps/secp256k1 && \
    cd secp256k1 && ./autogen.sh && ./configure --enable-module-recovery --enable-experimental --enable-module-ecdh && \
    make && make install && cd .. && rm -rf secp256k1

WORKDIR /strato-platform 